### PR TITLE
Adding necessary puppetlabs/ruby dependency

### PR DESCRIPTION
**Pull request by andyleejordan**
Morning!

Your module includes ruby::params but does not specify any dependency. This seems to fix it.

### CODE REVIEW

**Comment by MattiSG** [comment]
Based on my testing, this on its own is not enough to remove the `Error: Could not find class ruby::params`. You actually need to have the `puppetlabs/ruby` dependency installed alongside the `puppet-bundler` module. And then, if it is, there's no need to specify it explicitly.

_(disclaimer: I am not an expert in Puppet)_

**Comment by andyleejordan** [comment]
When installed with `puppet forge install puppet-bundler`, this Modulefile tells Forge to resolve the listed dependencies automatically, thus ensuring that puppetlabs/ruby gets installed.

**Comment by MattiSG** [comment]
@andschwa Ok, I suspected there was something like bundler for Puppet (“forge”, then), but we are not using it atm. Sorry for my comment.

I opened a PR #2 with user-level documentation for the same problem. I guess both approaches are important. If this PR gets merged, then #2 has to be amended for Forge users.

**Comment by andyleejordan** [comment]
Um, I originally found your module through the forge: https://forge.puppetlabs.com/ploperations/bundler

If you haven't used forge yet, here's some documentation: http://docs.puppetlabs.com/puppet/2.7/reference/modules_publishing.html

**Comment by MattiSG** [comment]
@andschwa “my module”? Sorry, I think you're taking me for someone else  :)  Thanks for the refs though.

**Comment by andyleejordan** [comment]
Heh, you must not be part of the ploperations group then. I thought that seemed funny when you disclaimed not being an expert in Puppet, but I didn't make the connection that someone else might be commenting on my pull request, and not the owner of the repo, sorry about the confusion :) (but you did say 'we are not using it at the moment', which made up my mind about you owning the code, double sorry)

puppetlabs-operations needs to accept the pull request and resubmit the module to the forge, then when it's installed, the dependency will go away automatically.

**Comment by igalic** [comment]
The latest version of `puppetlabs/ruby` doesn't even have `ruby::params::gem_binpath`, so perhaps we should fix this by simply removing it from the `path`?

**Comment by igalic** [comment]
fixed this in #5

**Pull request merged**
